import type { SalaryRecord } from '@/types/salary'

export const mockSalaries: SalaryRecord[] = [
  // ─── Google ───────────────────────────────────────────────────────────────
  {
    id: 'g-001',
    company: 'Google',
    company_slug: 'google',
    role: 'Software Engineer',
    level: 'L3',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 1,
    base_salary: 1800000,
    bonus: 200000,
    stock: 400000,
    total_compensation: 2400000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.9,
    is_verified: true,
    submitted_at: '2024-10-01T10:00:00Z',
  },
  {
    id: 'g-002',
    company: 'Google',
    company_slug: 'google',
    role: 'Software Engineer',
    level: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 3,
    base_salary: 2800000,
    bonus: 450000,
    stock: 1200000,
    total_compensation: 4450000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.92,
    is_verified: true,
    submitted_at: '2024-10-05T10:00:00Z',
  },
  {
    id: 'g-003',
    company: 'Google',
    company_slug: 'google',
    role: 'Software Engineer',
    level: 'L5',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 6,
    base_salary: 4200000,
    bonus: 800000,
    stock: 2000000,
    total_compensation: 7000000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.95,
    is_verified: true,
    submitted_at: '2024-10-10T10:00:00Z',
  },
  {
    id: 'g-004',
    company: 'Google',
    company_slug: 'google',
    role: 'Software Engineer',
    level: 'L6',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 10,
    base_salary: 6500000,
    bonus: 1500000,
    stock: 5000000,
    total_compensation: 13000000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.88,
    is_verified: true,
    submitted_at: '2024-10-15T10:00:00Z',
  },
  {
    id: 'g-005',
    company: 'Google',
    company_slug: 'google',
    role: 'Product Manager',
    level: 'L5',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 7,
    base_salary: 4500000,
    bonus: 900000,
    stock: 2500000,
    total_compensation: 7900000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.87,
    is_verified: true,
    submitted_at: '2024-10-18T10:00:00Z',
  },
  {
    id: 'g-006',
    company: 'Google',
    company_slug: 'google',
    role: 'Staff Engineer',
    level: 'STAFF',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 12,
    base_salary: 8000000,
    bonus: 2000000,
    stock: 8000000,
    total_compensation: 18000000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.91,
    is_verified: true,
    submitted_at: '2024-11-01T10:00:00Z',
  },

  // ─── Amazon ───────────────────────────────────────────────────────────────
  {
    id: 'a-001',
    company: 'Amazon',
    company_slug: 'amazon',
    role: 'Software Development Engineer',
    level: 'SDE_I',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 1,
    base_salary: 1600000,
    bonus: 300000,
    stock: 500000,
    total_compensation: 2400000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.9,
    is_verified: true,
    submitted_at: '2024-09-01T10:00:00Z',
  },
  {
    id: 'a-002',
    company: 'Amazon',
    company_slug: 'amazon',
    role: 'Software Development Engineer',
    level: 'SDE_II',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2600000,
    bonus: 500000,
    stock: 1500000,
    total_compensation: 4600000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.93,
    is_verified: true,
    submitted_at: '2024-09-05T10:00:00Z',
  },
  {
    id: 'a-003',
    company: 'Amazon',
    company_slug: 'amazon',
    role: 'Software Development Engineer',
    level: 'SDE_III',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 8,
    base_salary: 4200000,
    bonus: 0,
    stock: 3500000,
    total_compensation: 7700000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.89,
    is_verified: true,
    submitted_at: '2024-09-10T10:00:00Z',
  },
  {
    id: 'a-004',
    company: 'Amazon',
    company_slug: 'amazon',
    role: 'Principal Engineer',
    level: 'PRINCIPAL',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 15,
    base_salary: 9000000,
    bonus: 2500000,
    stock: 15000000,
    total_compensation: 26500000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.85,
    is_verified: false,
    submitted_at: '2024-09-20T10:00:00Z',
  },
  {
    id: 'a-005',
    company: 'Amazon',
    company_slug: 'amazon',
    role: 'Software Development Engineer',
    level: 'SDE_II',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 5,
    base_salary: 2500000,
    bonus: 450000,
    stock: 1200000,
    total_compensation: 4150000,
    source: 'SCRAPED',
    confidence_score: 0.65,
    is_verified: false,
    submitted_at: '2024-10-01T10:00:00Z',
  },
  {
    id: 'a-006',
    company: 'Amazon',
    company_slug: 'amazon',
    role: 'Product Manager',
    level: 'L5',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 6,
    base_salary: 3800000,
    bonus: 700000,
    stock: 2000000,
    total_compensation: 6500000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.88,
    is_verified: true,
    submitted_at: '2024-10-12T10:00:00Z',
  },

  // ─── Meta ─────────────────────────────────────────────────────────────────
  {
    id: 'm-001',
    company: 'Meta',
    company_slug: 'meta',
    role: 'Software Engineer',
    level: 'IC4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 4,
    base_salary: 3500000,
    bonus: 700000,
    stock: 2800000,
    total_compensation: 7000000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.91,
    is_verified: true,
    submitted_at: '2024-10-03T10:00:00Z',
  },
  {
    id: 'm-002',
    company: 'Meta',
    company_slug: 'meta',
    role: 'Software Engineer',
    level: 'IC5',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 8,
    base_salary: 5500000,
    bonus: 1200000,
    stock: 6000000,
    total_compensation: 12700000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.9,
    is_verified: true,
    submitted_at: '2024-10-08T10:00:00Z',
  },
  {
    id: 'm-003',
    company: 'Meta',
    company_slug: 'meta',
    role: 'Data Scientist',
    level: 'IC4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 5,
    base_salary: 3200000,
    bonus: 600000,
    stock: 2500000,
    total_compensation: 6300000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.86,
    is_verified: true,
    submitted_at: '2024-11-05T10:00:00Z',
  },

  // ─── Microsoft ────────────────────────────────────────────────────────────
  {
    id: 'ms-001',
    company: 'Microsoft',
    company_slug: 'microsoft',
    role: 'Software Engineer',
    level: 'L4',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 3,
    base_salary: 2400000,
    bonus: 400000,
    stock: 1000000,
    total_compensation: 3800000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.88,
    is_verified: true,
    submitted_at: '2024-09-15T10:00:00Z',
  },
  {
    id: 'ms-002',
    company: 'Microsoft',
    company_slug: 'microsoft',
    role: 'Software Engineer',
    level: 'L5',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 7,
    base_salary: 3800000,
    bonus: 700000,
    stock: 2200000,
    total_compensation: 6700000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.92,
    is_verified: true,
    submitted_at: '2024-09-20T10:00:00Z',
  },
  {
    id: 'ms-003',
    company: 'Microsoft',
    company_slug: 'microsoft',
    role: 'Principal Engineer',
    level: 'PRINCIPAL',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 14,
    base_salary: 7500000,
    bonus: 2000000,
    stock: 10000000,
    total_compensation: 19500000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.84,
    is_verified: false,
    submitted_at: '2024-10-22T10:00:00Z',
  },
  {
    id: 'ms-004',
    company: 'Microsoft',
    company_slug: 'microsoft',
    role: 'Product Manager',
    level: 'L4',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2600000,
    bonus: 500000,
    stock: 900000,
    total_compensation: 4000000,
    source: 'SCRAPED',
    confidence_score: 0.62,
    is_verified: false,
    submitted_at: '2024-10-28T10:00:00Z',
  },

  // ─── Flipkart ─────────────────────────────────────────────────────────────
  {
    id: 'fk-001',
    company: 'Flipkart',
    company_slug: 'flipkart',
    role: 'Software Development Engineer',
    level: 'SDE_I',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 1,
    base_salary: 1400000,
    bonus: 150000,
    stock: 300000,
    total_compensation: 1850000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.87,
    is_verified: true,
    submitted_at: '2024-08-10T10:00:00Z',
  },
  {
    id: 'fk-002',
    company: 'Flipkart',
    company_slug: 'flipkart',
    role: 'Software Development Engineer',
    level: 'SDE_II',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2300000,
    bonus: 350000,
    stock: 900000,
    total_compensation: 3550000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.9,
    is_verified: true,
    submitted_at: '2024-08-15T10:00:00Z',
  },
  {
    id: 'fk-003',
    company: 'Flipkart',
    company_slug: 'flipkart',
    role: 'Software Development Engineer',
    level: 'SDE_III',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 8,
    base_salary: 3800000,
    bonus: 600000,
    stock: 2000000,
    total_compensation: 6400000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.88,
    is_verified: true,
    submitted_at: '2024-08-20T10:00:00Z',
  },
  {
    id: 'fk-004',
    company: 'Flipkart',
    company_slug: 'flipkart',
    role: 'Data Analyst',
    level: 'L3',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 2,
    base_salary: 1200000,
    bonus: 100000,
    stock: 0,
    total_compensation: 1300000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.85,
    is_verified: true,
    submitted_at: '2024-09-01T10:00:00Z',
  },

  // ─── Meesho ───────────────────────────────────────────────────────────────
  {
    id: 'me-001',
    company: 'Meesho',
    company_slug: 'meesho',
    role: 'Software Development Engineer',
    level: 'SDE_I',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 1,
    base_salary: 1300000,
    bonus: 100000,
    stock: 400000,
    total_compensation: 1800000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.83,
    is_verified: true,
    submitted_at: '2024-07-10T10:00:00Z',
  },
  {
    id: 'me-002',
    company: 'Meesho',
    company_slug: 'meesho',
    role: 'Software Development Engineer',
    level: 'SDE_II',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2100000,
    bonus: 300000,
    stock: 1000000,
    total_compensation: 3400000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.86,
    is_verified: true,
    submitted_at: '2024-07-15T10:00:00Z',
  },
  {
    id: 'me-003',
    company: 'Meesho',
    company_slug: 'meesho',
    role: 'Product Manager',
    level: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 5,
    base_salary: 2800000,
    bonus: 500000,
    stock: 1500000,
    total_compensation: 4800000,
    source: 'SCRAPED',
    confidence_score: 0.6,
    is_verified: false,
    submitted_at: '2024-08-01T10:00:00Z',
  },

  // ─── NVIDIA ───────────────────────────────────────────────────────────────
  {
    id: 'nv-001',
    company: 'NVIDIA',
    company_slug: 'nvidia',
    role: 'Software Engineer',
    level: 'L4',
    location: 'Pune',
    currency: 'INR',
    experience_years: 4,
    base_salary: 3200000,
    bonus: 600000,
    stock: 3000000,
    total_compensation: 6800000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.9,
    is_verified: true,
    submitted_at: '2024-09-05T10:00:00Z',
  },
  {
    id: 'nv-002',
    company: 'NVIDIA',
    company_slug: 'nvidia',
    role: 'Senior Software Engineer',
    level: 'L5',
    location: 'Pune',
    currency: 'INR',
    experience_years: 8,
    base_salary: 5000000,
    bonus: 1000000,
    stock: 8000000,
    total_compensation: 14000000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.88,
    is_verified: true,
    submitted_at: '2024-09-12T10:00:00Z',
  },

  // ─── Razorpay ─────────────────────────────────────────────────────────────
  {
    id: 'rp-001',
    company: 'Razorpay',
    company_slug: 'razorpay',
    role: 'Software Development Engineer',
    level: 'SDE_I',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 2,
    base_salary: 1600000,
    bonus: 150000,
    stock: 600000,
    total_compensation: 2350000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.85,
    is_verified: true,
    submitted_at: '2024-08-05T10:00:00Z',
  },
  {
    id: 'rp-002',
    company: 'Razorpay',
    company_slug: 'razorpay',
    role: 'Software Development Engineer',
    level: 'SDE_II',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 5,
    base_salary: 2600000,
    bonus: 400000,
    stock: 1800000,
    total_compensation: 4800000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.89,
    is_verified: true,
    submitted_at: '2024-08-12T10:00:00Z',
  },
  {
    id: 'rp-003',
    company: 'Razorpay',
    company_slug: 'razorpay',
    role: 'Staff Engineer',
    level: 'STAFF',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 11,
    base_salary: 6000000,
    bonus: 1200000,
    stock: 7000000,
    total_compensation: 14200000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.87,
    is_verified: true,
    submitted_at: '2024-08-20T10:00:00Z',
  },

  // ─── Zepto ────────────────────────────────────────────────────────────────
  {
    id: 'z-001',
    company: 'Zepto',
    company_slug: 'zepto',
    role: 'Software Development Engineer',
    level: 'SDE_I',
    location: 'Mumbai',
    currency: 'INR',
    experience_years: 1,
    base_salary: 1500000,
    bonus: 200000,
    stock: 800000,
    total_compensation: 2500000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.82,
    is_verified: true,
    submitted_at: '2024-10-01T10:00:00Z',
  },
  {
    id: 'z-002',
    company: 'Zepto',
    company_slug: 'zepto',
    role: 'Software Development Engineer',
    level: 'SDE_II',
    location: 'Mumbai',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2400000,
    bonus: 400000,
    stock: 1500000,
    total_compensation: 4300000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.84,
    is_verified: true,
    submitted_at: '2024-10-08T10:00:00Z',
  },

  // ─── TCS ──────────────────────────────────────────────────────────────────
  {
    id: 'tcs-001',
    company: 'TCS',
    company_slug: 'tcs',
    role: 'Software Engineer',
    level: 'L3',
    location: 'Chennai',
    currency: 'INR',
    experience_years: 1,
    base_salary: 700000,
    bonus: 50000,
    stock: 0,
    total_compensation: 750000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.88,
    is_verified: true,
    submitted_at: '2024-07-01T10:00:00Z',
  },
  {
    id: 'tcs-002',
    company: 'TCS',
    company_slug: 'tcs',
    role: 'Senior Software Engineer',
    level: 'L4',
    location: 'Pune',
    currency: 'INR',
    experience_years: 5,
    base_salary: 1100000,
    bonus: 80000,
    stock: 0,
    total_compensation: 1180000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.87,
    is_verified: true,
    submitted_at: '2024-07-10T10:00:00Z',
  },
  {
    id: 'tcs-003',
    company: 'TCS',
    company_slug: 'tcs',
    role: 'Tech Lead',
    level: 'L5',
    location: 'Mumbai',
    currency: 'INR',
    experience_years: 9,
    base_salary: 1600000,
    bonus: 120000,
    stock: 0,
    total_compensation: 1720000,
    source: 'SCRAPED',
    confidence_score: 0.63,
    is_verified: false,
    submitted_at: '2024-07-18T10:00:00Z',
  },

  // ─── Infosys ──────────────────────────────────────────────────────────────
  {
    id: 'in-001',
    company: 'Infosys',
    company_slug: 'infosys',
    role: 'Systems Engineer',
    level: 'L3',
    location: 'Mysuru',
    currency: 'INR',
    experience_years: 1,
    base_salary: 650000,
    bonus: 40000,
    stock: 0,
    total_compensation: 690000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.86,
    is_verified: true,
    submitted_at: '2024-06-01T10:00:00Z',
  },
  {
    id: 'in-002',
    company: 'Infosys',
    company_slug: 'infosys',
    role: 'Senior Systems Engineer',
    level: 'L4',
    location: 'Pune',
    currency: 'INR',
    experience_years: 4,
    base_salary: 1000000,
    bonus: 70000,
    stock: 0,
    total_compensation: 1070000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.85,
    is_verified: true,
    submitted_at: '2024-06-10T10:00:00Z',
  },
  {
    id: 'in-003',
    company: 'Infosys',
    company_slug: 'infosys',
    role: 'Tech Lead',
    level: 'L5',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 8,
    base_salary: 1500000,
    bonus: 100000,
    stock: 0,
    total_compensation: 1600000,
    source: 'SCRAPED',
    confidence_score: 0.6,
    is_verified: false,
    submitted_at: '2024-06-20T10:00:00Z',
  },

  // ─── Wipro ────────────────────────────────────────────────────────────────
  {
    id: 'wp-001',
    company: 'Wipro',
    company_slug: 'wipro',
    role: 'Software Engineer',
    level: 'L3',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 2,
    base_salary: 750000,
    bonus: 50000,
    stock: 0,
    total_compensation: 800000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.84,
    is_verified: true,
    submitted_at: '2024-06-05T10:00:00Z',
  },
  {
    id: 'wp-002',
    company: 'Wipro',
    company_slug: 'wipro',
    role: 'Senior Software Engineer',
    level: 'L4',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 6,
    base_salary: 1200000,
    bonus: 90000,
    stock: 0,
    total_compensation: 1290000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.83,
    is_verified: true,
    submitted_at: '2024-06-15T10:00:00Z',
  },

  // ─── USD records (San Francisco / London) ─────────────────────────────────
  {
    id: 'g-sf-001',
    company: 'Google',
    company_slug: 'google',
    role: 'Software Engineer',
    level: 'L5',
    location: 'San Francisco',
    currency: 'USD',
    experience_years: 7,
    base_salary: 22000000,
    bonus: 4000000,
    stock: 10000000,
    total_compensation: 36000000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.93,
    is_verified: true,
    submitted_at: '2024-11-10T10:00:00Z',
  },
  {
    id: 'a-sf-001',
    company: 'Amazon',
    company_slug: 'amazon',
    role: 'Software Development Engineer',
    level: 'SDE_II',
    location: 'San Francisco',
    currency: 'USD',
    experience_years: 5,
    base_salary: 17500000,
    bonus: 2000000,
    stock: 8000000,
    total_compensation: 27500000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.9,
    is_verified: true,
    submitted_at: '2024-11-12T10:00:00Z',
  },
  {
    id: 'ms-ld-001',
    company: 'Microsoft',
    company_slug: 'microsoft',
    role: 'Software Engineer',
    level: 'L5',
    location: 'London',
    currency: 'GBP',
    experience_years: 6,
    base_salary: 11000000,
    bonus: 1500000,
    stock: 4000000,
    total_compensation: 16500000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.87,
    is_verified: true,
    submitted_at: '2024-11-15T10:00:00Z',
  },

  // ─── Edge cases ───────────────────────────────────────────────────────────

  // Zero bonus, zero stock — TC must equal base exactly
  {
    id: 'edge-001',
    company: 'Wipro',
    company_slug: 'wipro',
    role: 'Data Analyst',
    level: 'L3',
    location: 'Delhi',
    currency: 'INR',
    experience_years: 2,
    base_salary: 900000,
    bonus: 0,
    stock: 0,
    total_compensation: 900000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.8,
    is_verified: true,
    submitted_at: '2024-05-01T10:00:00Z',
  },

  // Zero bonus only — TC = base + stock
  {
    id: 'edge-002',
    company: 'Amazon',
    company_slug: 'amazon',
    role: 'Software Development Engineer',
    level: 'SDE_III',
    location: 'Pune',
    currency: 'INR',
    experience_years: 9,
    base_salary: 4000000,
    bonus: 0,
    stock: 4000000,
    total_compensation: 8000000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.88,
    is_verified: true,
    submitted_at: '2024-05-10T10:00:00Z',
  },

  // Very high equity — NVIDIA-style
  {
    id: 'edge-003',
    company: 'NVIDIA',
    company_slug: 'nvidia',
    role: 'Principal Engineer',
    level: 'PRINCIPAL',
    location: 'Pune',
    currency: 'INR',
    experience_years: 16,
    base_salary: 9000000,
    bonus: 2000000,
    stock: 40000000,
    total_compensation: 51000000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.82,
    is_verified: false,
    submitted_at: '2024-05-20T10:00:00Z',
  },

  // Principal level — rarest tier
  {
    id: 'edge-004',
    company: 'Google',
    company_slug: 'google',
    role: 'Distinguished Engineer',
    level: 'PRINCIPAL',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 18,
    base_salary: 12000000,
    bonus: 4000000,
    stock: 25000000,
    total_compensation: 41000000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.79,
    is_verified: false,
    submitted_at: '2024-04-01T10:00:00Z',
  },

  // Very long company name — layout stress test
  {
    id: 'edge-005',
    company: 'Tata Consultancy Services',
    company_slug: 'tata-consultancy-services',
    role: 'Enterprise Solutions Architect',
    level: 'L6',
    location: 'Mumbai',
    currency: 'INR',
    experience_years: 12,
    base_salary: 2800000,
    bonus: 200000,
    stock: 0,
    total_compensation: 3000000,
    source: 'SCRAPED',
    confidence_score: 0.58,
    is_verified: false,
    submitted_at: '2024-04-10T10:00:00Z',
  },

  // Very large INR number — crore formatting test
  {
    id: 'edge-006',
    company: 'Google',
    company_slug: 'google',
    role: 'VP Engineering',
    level: 'L6',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 20,
    base_salary: 40000000,
    bonus: 10000000,
    stock: 60000000,
    total_compensation: 110000000,
    source: 'AI_INFERRED',
    confidence_score: 0.5,
    is_verified: false,
    submitted_at: '2024-03-01T10:00:00Z',
  },

  // Low confidence unverified scraped record
  {
    id: 'edge-007',
    company: 'Infosys',
    company_slug: 'infosys',
    role: 'Principal Consultant',
    level: 'PRINCIPAL',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 16,
    base_salary: 3500000,
    bonus: 300000,
    stock: 500000,
    total_compensation: 4300000,
    source: 'AI_INFERRED',
    confidence_score: 0.45,
    is_verified: false,
    submitted_at: '2024-03-15T10:00:00Z',
  },

  // Delhi location record
  {
    id: 'del-001',
    company: 'Microsoft',
    company_slug: 'microsoft',
    role: 'Software Engineer',
    level: 'L4',
    location: 'Delhi',
    currency: 'INR',
    experience_years: 3,
    base_salary: 2200000,
    bonus: 350000,
    stock: 800000,
    total_compensation: 3350000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.86,
    is_verified: true,
    submitted_at: '2024-10-25T10:00:00Z',
  },

  // Remote record
  {
    id: 'rem-001',
    company: 'Razorpay',
    company_slug: 'razorpay',
    role: 'Software Development Engineer',
    level: 'SDE_II',
    location: 'Remote',
    currency: 'INR',
    experience_years: 5,
    base_salary: 2400000,
    bonus: 350000,
    stock: 1200000,
    total_compensation: 3950000,
    source: 'CONTRIBUTOR',
    confidence_score: 0.83,
    is_verified: true,
    submitted_at: '2024-11-20T10:00:00Z',
  },
]

// Derived helpers used by frontend components

export const COMPANIES = [...new Set(mockSalaries.map((s) => s.company))].sort()

export const LOCATIONS = [...new Set(mockSalaries.map((s) => s.location))].sort()

export const ROLES = [...new Set(mockSalaries.map((s) => s.role))].sort()

export const LEVELS = [
  'L3', 'L4', 'L5', 'L6',
  'SDE_I', 'SDE_II', 'SDE_III',
  'STAFF', 'PRINCIPAL', 'IC4', 'IC5',
] as const

export function getSalariesByCompany(slug: string): SalaryRecord[] {
  return mockSalaries
    .filter((s) => s.company_slug === slug)
    .sort((a, b) => b.total_compensation - a.total_compensation)
}

export function getCompanySlugs(): string[] {
  return [...new Set(mockSalaries.map((s) => s.company_slug))]
}

export function computeMedian(values: number[]): number {
  if (values.length === 0) return 0
  const sorted = [...values].sort((a, b) => a - b)
  const mid = Math.floor(sorted.length / 2)
  return sorted.length % 2 !== 0
    ? (sorted[mid] ?? 0)
    : Math.round(((sorted[mid - 1] ?? 0) + (sorted[mid] ?? 0)) / 2)
}

export function getLevelDistribution(slug: string): Record<string, number> {
  const records = getSalariesByCompany(slug)
  return records.reduce<Record<string, number>>((acc, r) => {
    acc[r.level] = (acc[r.level] ?? 0) + 1
    return acc
  }, {})
}